### ISSUE TITLE
Displaying the Battle Screen

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project#1]
## Value Proposition

- As a player
- I want to see the battle screen
- in order to prepare for the upcoming battle.

## Description

![us1](https://user-images.githubusercontent.com/100302405/227489144-b86ec615-b5ff-4d2e-83d4-6176008aaa0d.png)

## Acceptance criteria

- [ ] The battle screen should display the player's and opponent's 
        Pokemon, their names, and their HP bars.

## Tasks

- [ ] Create the battle screen component.
- [ ] Implement logic to display the Pokemon, their names, and their 
        HP bars.
- [ ] Write tests to ensure the functionality is working as intended.
- [ ] Create a  folder with ressources.
