### ISSUE TITLE
Implementing Trainer Selection Menu

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project#17]
## Value Proposition

**As a player
**I want to be able to select one of three different trainers to battle with
**in order to choose my difficulty level and have a challenging and exciting battle experience.
​
## Description

![us8](https://user-images.githubusercontent.com/100302405/231187866-cc18974d-f06f-442e-975b-2c04c24278e6.png)

A trainer selection menu should be added to the game, allowing the player to choose one of three available enemy trainers for battle. Each trainer should have a different difficulty level, with the first being the easiest and the last being the most difficult. The Pokemon of the selected trainer should then be pitted against the player's Pokemon. The battle screen should be updated to show the Pokemon he is using.
​
## Acceptance Criteria

- [x] A trainer selection menu should be added to the game.
- [x]  The player should be able to select one of three available enemy trainers to fight with.
- [x]  Each trainer should have a different difficulty level.
- [x]  The selected trainer's Pokemon should then battle the player's selected Pokemon.
- [x]  The battle screen should be updated to show the names and status values of the selected Pokemon of the generic trainer.

## Tasks

- [x] Create a component for the trainer selection menu.
- [x] Implement logic that allows the player to select one of three available trainers to fight with.
- [x] Each trainer should have a different difficulty level.
- [x] To do this, the previous array must be expanded to add the new enemy Pokemon and their status values.

**Comment by nikokreissl** [comment]
Love the app and great US! 😊

**Comment by dennisbuchwald** [comment]
@nikokreissl I'm very happy about that, I'll post the QA of the current version right away (after the code review). Feel free to try out the app! 😊
