### ISSUE TITLE
Implementing the Attack Functionality and Winning Condition

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project#2]
## Value Proposition

- As a player
- I want to be able to attack the opponent's Pokemon
- in order to defeat them and feel accomplished.

## Description

![us2](https://user-images.githubusercontent.com/100302405/227528561-dcae3059-a3a8-4a15-a1e9-d8f22335db9a.png)

After the battle screen is displayed, the player should be prompted with the question "Klicke auf "Kampf" um anzugreifen" and presented with a button labeled "Kampf". When the player selects the "Kampf" button, a fixed amount of the opponent's HP should be deducted, based on the strength of the player's Pokemon attack. If the opponent's HP reaches zero, the battle is won and the player should be presented with a message "Du hast den Kampf gewonnen" and given the option to return to the previous menu.

## Acceptance criteria

- [ ] The player should be prompted with the question "Klicke auf "Kampf" um anzugreifen" and presented with a button labeled "Kampf".
- [ ] When the player selects the "Attack" button, a fixed amount of the opponent's HP should be deducted based on the strength of the player's Pokemon attack.
- [ ] If the opponent's HP reaches zero, the player should be presented with a message "Du hast den Kampf gewonnen."

## Tasks

- [ ] Add the "Klicke auf "Kampf" um anzugreifen" prompt and the "Kampf" button to the battle screen.
- [ ] Implement the attack functionality based on the strength of the player's Pokemon attack.
- [ ] Deduct the fixed amount of opponent's HP when the player attacks.
- [ ]  If the opponent's HP reaches zero, display a message "Du hast den Kampf gewonnen." and give the option to return to the previous menu.
- [ ] Write tests to ensure the functionality is working as intended.
- [ ] Update the battle screen to display changes in opponent's HP after being attacked.
