### ISSUE TITLE
Adding Sound Effects for Menus, Battle Music, and Attacks

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project#29]
## Value Proposition

As a player
I would like to have adequate sound effects during menus, battles and attacks
to have a more intense and enjoyable experience.
​
## Description

Appropriate sound effects should be added to the game, including a menu sound effect for menu interactions and a battle music track for the battle screen. Additionally, each attack should have its own unique sound effect to enhance the player's immersion in the game.
​
## Acceptance Criteria

- [ ] A menu sound effect should be added for menu interactions.
- [ ] Each difficulty level has its own Music
- [ ] The win screen has its own music
- [ ] The loser screen has its own music

## Tasks

- [x] add new sounds to `useSoundEffect.js
- [x] search for new music and add it to the repository 
- [x] add music to menu
- [x] add music to the win screen
- [x] add music to the loser screen
- [x] rewrite the existing music so that it is only played during combat

**Comment by ella-blaupause** [comment]
I do not understand what a menu sound effect is.
What happens in a menu sound effect?

**Comment by dennisbuchwald** [comment]
hey @ella-blaupause , yes I know, a user story about sound effects is pretty abstract.  Currently there is music and sound FX in the game, I would like to revise them. The music that currently runs is for example the music that should only come in the fight, during the selection menus I want to run a different soundtrack. This is what I want to rework with this user story, just try the [App](https://capstone-project-pokemon-battler-app.vercel.app/), then it will be clearer.

**Comment by Gblur** [comment]
LGTM
