### ISSUE TITLE
Implementing Enemy Attack Functionality

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project#3]
## Value Proposition

- As a player
- I want to be able to be attacked by the opponent's Pokemon
- in order to experience a real battle and strategize my attacks.

## Description

![Image](https://user-images.githubusercontent.com/100302405/227507918-e5051032-90e6-4ce6-b383-8490d8ee0af7.png)

After the player attacks the opponent's Pokemon, the opponent's Pokemon should automatically attack back, deducting a fixed amount of the player's Pokemon HP. The player should not have input during the opponent's attack. After the opponent's attack, the player should be prompted with the question "What do you want to do?" and presented with the "Attack" button again to continue the battle.

## Acceptance criteria

- [ ]  After the player attacks the opponent's Pokemon, the opponent's Pokemon should automatically attack back and deduct a fixed amount of the player's Pokemon HP.
- [ ] The player should not have input during the opponent's attack.
- [ ] After the opponent's attack, the player should be prompted with the question "Was willst du tun?" and presented with the "Kampf" button again to continue the battle.

## Tasks

- [ ] Implement the enemy attack functionality and deduct a fixed amount of player's Pokemon HP.
- [ ] Disable player input during the opponent's attack.
- [ ] Update the battle screen to display changes in player's Pokemon HP after being attacked.
- [ ]  Prompt the player with the question "What do you want to do?" and present the "Attack" button after the opponent's attack.
- [ ] Write tests to ensure the functionality is working as intended.

**Comment by Efendi5** [comment]
Was ist mit dem Text "Du hast gewonnen", falls der Kampf gewonnen wird?
Diese Option würde ich auch noch hinzufügen in diese User Story

**Comment by dennisbuchwald** [comment]
Die passiert schon in der der story davor. 😊
